-- Human-readable contract reference (CON/2026/0004) shown on the contract
-- list and form. Generated by a sequence so concurrent inserts cannot collide.
CREATE SEQUENCE IF NOT EXISTS contract_number_seq;

ALTER TABLE contracts
    ADD COLUMN contract_number TEXT UNIQUE
        DEFAULT 'CON/' || to_char(now(), 'YYYY') || '/' ||
                lpad(nextval('contract_number_seq')::text, 4, '0'),
    ADD COLUMN notes TEXT;

-- Any rows created before this column existed.
UPDATE contracts
   SET contract_number = 'CON/' || to_char(start_date, 'YYYY') || '/' ||
                         lpad(nextval('contract_number_seq')::text, 4, '0')
 WHERE contract_number IS NULL;

CREATE INDEX idx_contracts_status ON contracts (status);
